myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("platinum/", include("platinum.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platinum/urls.py
from django.urls import path
from . import views

app_name = "platinum"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("oil/<int:pk>/", views.OilDetailView.as_view(), name="oil_detail"),
    path("brand/<int:pk>/", views.BrandDetailView.as_view(), name="brand_detail"),
    path("contacts/", views.contacts, name="contacts"),
    path("search/", views.search, name="search"),
    path("cart/", views.cart, name="cart"),
    path("add/order/", views.add_order, name="add_order"),
    path("process/order/", views.process_order, name="process_order"),


]

platinum/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Brand(models.Model):
    name = models.CharField(max_length=50)
    prod_country = models.CharField(max_length=50)
    img = models.ImageField(null=True, blank=True, upload_to="brands/")

    def __str__(self):
        return self.name

    def url(self):
        return reverse("platinum:brand_detail", args=[self.id])

    class Meta:
        ordering = ["name"]


class Oil(models.Model):
    type = models.CharField(max_length=50)
    w_visco = models.IntegerField(default=0)
    s_visco = models.IntegerField(default=0)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    standard = models.ManyToManyField("Standard", related_name="oils")

    def __str__(self):
        return f"{self.brand} {self.w_visco}W-{self.s_visco}"

    def url(self):
        return reverse("platinum:oil_detail", args=[self.id])

    def get_visco(self):
        return f"{self.w_visco}W-{self.s_visco}"

    class Meta:
        ordering = ["brand"]


class Standard(models.Model):
    st_name = models.CharField(max_length=50)
    st_value = models.CharField(max_length=20)

    def __str__(self):
        return str(self.st_name) + " " + str(self.st_value)


class OilInstance(models.Model):
    oil = models.ForeignKey(Oil, on_delete=models.SET_NULL, null=True)
    mark = models.CharField(max_length=50, null=True, blank=True)
    price = models.FloatField(default=0)
    volume = models.FloatField(default=0)
    img = models.ImageField(null=True, blank=True, upload_to="oils/")

    def get_discount(self):
        return round(self.price * 0.95, 2)

    class Meta:
        ordering = ["oil"]

    def __str__(self):
        return f"{self.oil} {self.mark} {self.volume}L"


class Cart(models.Model):
    oil = models.ForeignKey(OilInstance, on_delete=models.CASCADE, null=True)
    amount = models.PositiveIntegerField(default=0, null=True)
    ORDER_STATUS = (("d", "Done"), ("w", "In work"),)
    status = models.CharField(max_length=1, choices=ORDER_STATUS, default="w")

    def get_sum(self):
        return self.amount * self.oil.price

    def get_sum_discount(self):
        return self.amount * self.oil.get_discount()

platinum/forms.py
from django.forms import ModelForm
from .models import *


class CartModelForm(ModelForm):
    class Meta:
        model = Cart
        fields = ["oil", "amount"]

platinum/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from rest_framework import generics
from django.contrib.auth import authenticate

from .models import *
from .forms import *
from rest_framework.renderers import JSONRenderer
from .serializers import *
import json


class IndexView(ListView):
    model = Brand
    template_name = "platinum/index.html"
    context_object_name = "brands"


class OilDetailView(DetailView):
    model = Oil

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["oil_instances"] = OilInstance.objects.all()
        context["standards"] = Standard.objects.all()
        return context


class BrandDetailView(DetailView):
    model = Brand

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["motor_oils"] = Oil.objects.filter(type__icontains="motor")
        context["transmission_oils"] = Oil.objects.filter(type__icontains="trans")
        context["standards"] = Standard.objects.all()
        return context


def contacts(request):
    context = {
        "phone": "(099) 999-99-99",
        "address": "Восточная ул., 9, Запорожье, Запорожская область, 69000",
        "manager": "Revenets Dmytrij",
    }
    return render(request, "platinum/contacts.html", context)


def search(request):
    string = request.POST.get("search")

    if string:
        context = {
            "string": string,
            "brands": Brand.objects.filter(name__icontains=string),
            "oils": Oil.objects.filter(Q(w_visco__icontains=string[:1]) | Q(s_visco__icontains=string[-2:])),
        }
        return render(request, 'platinum/search.html', context)
    return HttpResponseRedirect(reverse("platinum:index"))


def cart(request):
    context = {
        "order_form": CartModelForm(),
        "order": Cart.objects.filter(status__iexact="w"),

    }
    return render(request, "platinum/cart.html", context)


def add_order(request):
    form = CartModelForm(request.POST)
    saved = form.save(commit=False)
    saved.save()
    return HttpResponseRedirect(reverse("platinum:cart"))


def process_order(request):
    orders = Cart.objects.filter(status__iexact="w")
    order = {
        "name": [],
        "oil": [],
        "amount": [],
        "price": [],
    }
    for data in orders:
        order["oil"].append(str(data.oil))
        order["amount"].append(data.amount)
        if request.user.is_authenticated:
            order["name"].append(str(request.user.get_full_name()))
            order["price"].append(data.oil.get_discount())
        data.status = "d"
        data.save()
    order_list = {
        "order": order,
    }
    with open("order.json", "a", newline="\n") as file:
        json.dump(order_list, file, indent=3)
    return HttpResponseRedirect(reverse("platinum:index"))

platinum/templates/platinum/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'platinum/css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'platinum/img/favicon.png' %}"/>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
        <a class="navbar-brand" href="{% url 'platinum:index' %}">
            <img src="{% static 'platinum/img/favicon.png' %}" width="60" height="60" class="d-inline-block align-top"
                 alt="">
            <b>Platinum-2010</b>
        </a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">
                        User: <b>{{ user.get_full_name }}</b> <br> Click to log out
                        <span class="sr-only"></span></a>
                    {% else %}
                    <a class="nav-link" href="{% url 'login' %}"><b>Log In</b><span class="sr-only"></span></a>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% static 'platinum/xls/price.xlsx' %}" download>Price List<br> (download)</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="https://wixeurope.com/ua" target="_blank" rel="noopener noreferrer">Find a filter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://topoil.com.ua/specificacii-dopuski-masel-acea-a1-b1-a3-b3-b4-api-sn-sm-sl-gm-vw-504-507-506-01-506-00-505-01-505-00-ilsac-gf-5-sae-5w30-5w40-10w40-5w20-10w30"
                   target="_blank" rel="noopener noreferrer">Standards Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'platinum:contacts' %}">Contacts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'platinum:cart' %}">
                        <img src="{% static 'platinum/img/shopping-cart.png' %}" width="50">
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

        <form class="form-inline" method="post" action="{% url 'platinum:search' %}">
            {% csrf_token %}
            <input class="form-control" name="search"  type="search" placeholder="Search">
            <input class="btn btn-outline-success" type="submit" value="Search">
        </form>
    </nav>
    {% block content %}{% endblock %}
</div>
</body>
</html>

platinum/templates/platinum/brand_detail.html
{% extends 'platinum/base.html' %}

{% block title%}
{{ brand }}
{% endblock %}

{% block content%}
<h3>Motor oil "{{ brand }}"</h3>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Oil</th>
        <th colspan="2">Standards</th>
    </tr>
    </thead>
    {% for motor in motor_oils %}
    {% if motor.brand == brand %}
    <tr>
        <td><a href="{% url 'platinum:oil_detail' motor.id %}">{{ motor.brand }} {{ motor.w_visco }}W-{{ motor.s_visco }} {{ motor.mark }}</a></td>
        {% for oil_st in motor.standard.all %}
        {% for st in standards %}
        {% if oil_st == st %}
        <td> {{ st }} </td>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </tr>
    {% endif %}
    {% endfor %}
</table>

<hr>
<h3>Transmission oil "{{ brand }}"</h3>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Oil</th>
        <th>Standard</th>
    </tr>
    </thead>
    {% for tr in transmission_oils %}
    {% if tr.brand == brand %}
    <tr>
        <td><a href="{% url 'platinum:oil_detail' tr.id %}">
            {{ tr.brand }} {{ tr.w_visco }}W-{{ tr.s_visco }} {{ tr.mark }}
        </a></td>
        {% for oil_st in tr.standard.all %}
        {% for st in standards %}
        {% if oil_st == st %}
        <td> {{ st }} </td>
        {% endif %}
        {% endfor %}
        {% endfor %}
    </tr>
    {% endif %}

    {% endfor %}
</table>
{% endblock %}

platinum/templates/platinum/cart.html
{% extends 'platinum/base.html' %}

{% block title%}
Sales cart
{% endblock %}

{% block content%}

<h2 class="text-center">Make your order</h2>

<form method="post" action="{% url 'platinum:add_order' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ order_form.as_table }}
    </table>
    <input class="btn btn-outline-success" type="submit" value="Add to cart">
</form>
<hr>
<div class="row">
    <div class="col-10">
        <table class="table-bordered">
            <tr>
                <th colspan="2" class="text-center">Oil Instance</th>
                <th class="text-center">Amount</th>
                <th class="text-center">Price</th>
                <th class="text-center">Sum</th>
            </tr>
            {% for unit in order %}
            <tr>
                <td><img src="{{ unit.oil.img.url }}" class="img-fluid" style="height:80px"></td>
                <td>{{ unit.oil }}</td>
                <td align="center">{{ unit.amount }}</td>
                {% if user.is_authenticated %}
                <td>{{ unit.oil.get_discount }} &#8372</td>
                <td>{{ unit.get_sum_discount }} &#8372</td>
                {% else %}
                <td> {{ unit.oil.price }} &#8372 </td>
                <td>{{ unit.get_sum }} &#8372</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<form method="post" action="{% url 'platinum:process_order' %}">
    {% csrf_token %}
    <input class="btn btn-outline-success" type="submit" value="Order">
</form>
{% endblock %}

platinum/templates/platinum/contacts.html
{% extends 'platinum/base.html' %}

{% block title%}
Contacts
{% endblock %}

{% block content%}
<h2 style="text-align:center"> Contact information </h2>
<hr>
<div class="row">
    <div class="col-6">
        <div class="row">
            <h5><b>Manager: {{ manager }}</b></h5>
        </div>
        <div class="row">
            <h5><b>Phone: {{ phone }}</b></h5>
        </div>
        <div class="row">
            <h5><b>Address: {{ address }}</b></h5>
        </div>
        <div class="row">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2710.486159836347!2d35.22680301263721!3d47.79215278150678!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dc5e9791e1e195%3A0xded69479dcd6080a!2z0JLQvtGB0YLQvtGH0L3QsNGPINGD0LsuLCA5LCDQl9Cw0L_QvtGA0L7QttGM0LUsINCX0LDQv9C-0YDQvtC20YHQutCw0Y8g0L7QsdC70LDRgdGC0YwsIDY5MDAw!5e0!3m2!1sru!2sua!4v1624562222032!5m2!1sru!2sua" width="450" height="350" style="border:0; " allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>
    <div class="col-6" align="center">
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd8LpZFwdJUgvq74yaybFpnAZLXLtLnOg7fG0QFdvIqpGyYJg/viewform?embedded=true" width="550" height="500" frameborder="0" marginheight="0" marginwidth="0">Загрузка…</iframe>

    </div>
</div>
{% endblock %}

platinum/templates/platinum/index.html
{% extends 'platinum/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'platinum/css/style.css' %}">
{% block title%}
Platinum-2010
{% endblock %}

{% block content%}
<h2 class="text-center" style="font-family: Arial">TOP BRANDS</h2>
<div class="row">
    {% for brand in brands %}
    <div class="col-3 align-self-center">
        <div class="row my-2">
            <a href="{% url 'platinum:brand_detail' brand.id %}">
                <img src="{{ brand.img.url }}" class="img-fluid" style="width:200px">
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

platinum/templates/platinum/oil_detail.html
{% extends 'platinum/base.html' %}

{% block title%}
{{ oil }}
{% endblock %}

{% block content%}
<a href="{% url 'platinum:brand_detail' oil.brand.id %}"><b> <<< Back to {{ oil.brand }}</b></a>
{% for instance in oil_instances %}
{% if oil == instance.oil %}
<div class="row bg-light">
    <div class="col-2 text-center my-2">
        <img src="{{ instance.img.url }}" class="img-fluid" style="height:150px">
    </div>
    <div class="col-2 align-self-center">
        <h6>{{ oil }} {{ instance.mark }}</h6>
    </div>
    {% for oil_st in oil.standard.all %}
    {% for st in standards %}
    {% if oil_st == st %}
    <div class="col-2 align-self-center"><h6>{{st}}</h6></div>
    {% endif %}
    {% endfor %}
    {% endfor %}
    <div class="col-1 align-self-center">
        <h6> {{ instance.volume }} L </h6>
    </div>
    <div class="col-2 align-self-center">
        {% if user.is_authenticated %}
        <h6><s>{{ instance.price }} &#8372</s><br>
            {{ instance.get_discount }} &#8372
        </h6>
        {% else %}
        <h6> {{ instance.price }} &#8372</h6>
        {% endif %}
    </div>
<!--    <div class="col-1 align-self-center">-->
<!--        <form method="post" action="#">-->
<!--            <input name="amount" type="number" step="1" min="0" class="form-control input-sm">-->
<!--            <input type="submit" value="Buy" class="btn btn-outline-success">-->
<!--        </form>-->
<!--    </div>-->
</div>
{% endif %}
{% endfor %}

{% endblock %}

platinum/templates/platinum/search.html
{% extends 'platinum/base.html' %}

{% block title%}
Search
{% endblock %}

{% block content %}
<h1 class="text-center"> Search results </h1>
{% if brands %}
{% for brand in brands%}
<div class="row">
    <div class="col-2 my-2">
        <img src="{{ brand.img.url }}" class="img-fluid" width="100">
    </div>
    <div class="col-8 align-self-center">
        <h5><a href="{{ brand.url }}">{{ brand }}</a></h5>
    </div>
</div>
{% endfor%}

{% endif %}

{% if oils %}
{% for oil in oils %}
<div class="row">
    <div class="col-2 my-2">
        <img src="{{ oil.brand.img.url }}" class="img-fluid" width="100">
    </div>
    <div class="col-8 align-self-center">
        <h5><a href="{{ oil.url }}">{{ oil }}</a></h5>
    </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}